# https://pytorch-lightning.readthedocs.io/en/latest/api/pytorch_lightning.callbacks.ModelCheckpoint.html

# Save the model periodically by monitoring a quantity.
# Look at the above link for more detailed information.
model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath:  ${paths.root_dir}/checkpoints/  # directory to save the model file
  filename: {epoch}-{val/acc:4f} # checkpoint filename
  monitor: val/acc # name of the logged metric which determines when model is improving
  verbose: False # verbosity mode
  save_last: False # additionally always save an exact copy of the last checkpoint to a file last.ckpt
  save_top_k: 1 # save k best models (determined by above metric)
  mode: "max"
  auto_insert_metric_name: True
  save_weights_only: False
  every_n_train_steps: null
  train_time_interval: null
  every_n_epochs: null
  save_on_train_epoch_end: null
